# Generated by Django 4.2.5 on 2023-10-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
